
Metrics/LineLength:
  Max: 100

Style/MutableConstant:
  Enabled: false

# Lint/LiteralInCondition:
#   Enabled: false

Style/CommandLiteral:
  EnforcedStyle: mixed

AllCops:
  TargetRubyVersion: 2.4.1
